sudo: false

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
  - "pypy3"  # Pypy3 5.8.0-beta0

install:
  - pip install -e .[dev]

script:
  - python -m pytest --cov-config .coveragerc --cov=./
  - python benchmark.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
