language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
  - "pypy3"  # Pypy3 5.8.0-beta0
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage python -m pytest
after_success:
  - codecov
