sudo: false

dist: xenial

language: python

services:
  - mongodb

cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
  - "pypy3"  # Pypy3 5.8.0-beta0

before_script:
  - sleep 15
  - mongo vakt_db --eval 'db.createUser({user:"test_user",pwd:"test_password",roles:["readWrite"]});'

install:
  - pip install -e .[dev,mongo]

script:
  - make coverage
  - make bench

after_success:
  - bash <(curl -s https://codecov.io/bash)
