language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
  - "pypy3"  # Pypy3 5.8.0-beta0
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
script:
  - python -m pytest . --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
