dist: xenial   # required for Python >= 3.7

sudo: false

language: python

services:
  - mongodb
  - mysql
  - postgresql

cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7"
  - "3.7-dev"  # 3.7 development branch
#  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  - "pypy3.5"  # Pypy3 3.5.3

before_script:
  - sleep 15
  - mongo vakt_db --eval 'db.createUser({user:"test_user",pwd:"test_password",roles:["readWrite"]});'
  - mysql -e 'CREATE DATABASE vakt_db;'
  - psql -c 'create database vakt_db;' -U postgres

install:
  - make deps

script:
  # test all suites with coverages
  - DATABASE_DSN="sqlite:///:memory:" make coverage
  # test SQL integration for MySQL
  - DATABASE_DSN=mysql://root:@localhost/vakt_db make test-sql-i
  # test SQL integration for Postgres
  - DATABASE_DSN=postgresql+psycopg2://postgres:@localhost/vakt_db make test-sql-i
  - make bench

after_success:
  - bash <(curl -s https://codecov.io/bash)
